typography_spectrum: 0.5886225614269808
content_rating:
  adult: false
color:
  brandColors:
    - '#450003'
    - '#5C0002'
    - '#94090D'
    - '#D40D12'
    - '#FF1D23'
  brandStrength: 0.8592999780513715
  lightness: 0.5489566522453091
  saturation: 0.3966540753399714
  rhythmicContrast: 0.3132329555384188
github: true
layout_spectrum: 0.10557802644982418
author:
  name: ''
  email: yanay@pitch.studio
  url: 'http://pitch.studio'
name: Pitch
url: 'https://pitch.studio/pitch-main/'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: About us
    id: 20f2bb60-6800-4b4a-911f-253601254009
    type: content
title: Pitch
content: []
description: Rule your music
