typography_spectrum: 0.6500977953181298
content_rating:
  adult: false
color:
  brandColors:
    - '#2E0927'
    - '#D90000'
    - '#FF2D00'
    - '#FF8C00'
    - '#04756F'
  brandStrength: 0.17554155731702797
  lightness: 0.2950688078972778
  saturation: 0.49307775892566263
  rhythmicContrast: 0.7938552970583966
github: true
layout_spectrum: 0.04044905247701572
author:
  name: ''
  email: yanay@pitch.studio
  url: 'http://pitch.studio'
name: Pitch
url: 'https://pitch.studio/pitch-main/'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: About us
    id: d96e6de6-3f4f-414c-8498-49bb6be74b4c
    type: content
  - name: Music and you
    id: cb52ec0e-07dd-478f-bbb3-00b228020f6c
    type: content
  - name: Top Songs
    id: 6795025e-fa67-4085-bbee-87b9907d7429
    type: content
title: Pitch
content: []
description: Rule your music
